name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Clone Backend repository
        uses: actions/checkout@v2
        with:
          repository: AshishKingdom/Backend
          path: backend

      - name: Build Backend Docker image
        run: |
          docker build -t ashishkingdom/codedev:latest .
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ashishkingdom/codedev:latest
